enum class VERTEX_ATTRIBUTE : GL::GLenum
{ BYTE           = GL_BYTE
, UNSIGNED_BYTE  = GL_UNSIGNED_BYTE
, SHORT          = GL_SHORT
, UNSIGNED_SHORT = GL_UNSIGNED_SHORT
, INT            = GL_INT
, UNSIGNED_INT   = GL_UNSIGNED_INT

, HALF_FLOAT     = GL_HALF_FLOAT
, FLOAT          = GL_FLOAT
, DOUBLE         = GL_DOUBLE
, FIXED          = GL_FIXED

, INT_2_10_10_10_REV          = GL_INT_2_10_10_10_REV
, UNSIGNED_INT_2_10_10_10_REV = GL_UNSIGNED_INT_2_10_10_10_REV

, INT_8   = BYTE
, UINT_8  = UNSIGNED_BYTE
, INT_16  = SHORT
, UINT_16 = UNSIGNED_SHORT
, INT_32  = INT
, UINT_32 = UNSIGNED_INT

, BINARY16 = HALF_FLOAT
, BINARY32 = FLOAT
, BINARY64 = DOUBLE
};

#undef GL_BYTE
#undef GL_UNSIGNED_BYTE
#undef GL_SHORT
#undef GL_UNSIGNED_SHORT
#undef GL_INT
#undef GL_UNSIGNED_INT
#undef GL_HALF_FLOAT
#undef GL_FLOAT
#undef GL_DOUBLE
#undef GL_FIXED
#undef GL_INT_2_10_10_10_REV
#undef GL_UNSIGNED_2_10_10_10_REV

std::string to_string(VERTEX_ATTRIBUTE v){
  switch(v){
  case VERTEX_ATTRIBUTE::INT_8    : return "INT_8";
  case VERTEX_ATTRIBUTE::UINT_8   : return "UINT_8";
  case VERTEX_ATTRIBUTE::INT_16   : return "INT_16";
  case VERTEX_ATTRIBUTE::UINT_16  : return "UINT_16";
  case VERTEX_ATTRIBUTE::INT_32   : return "INT_32";
  case VERTEX_ATTRIBUTE::UINT_32  : return "UINT_32";
  case VERTEX_ATTRIBUTE::BINARY16 : return "BINARY16";
  case VERTEX_ATTRIBUTE::BINARY32 : return "BINARY32";
  case VERTEX_ATTRIBUTE::BINARY64 : return "BINARY64";
  case VERTEX_ATTRIBUTE::FIXED    : return "FIXED";
  case VERTEX_ATTRIBUTE::INT_2_10_10_10_REV          : return "GL_INT_2_10_10_10_REV";
  case VERTEX_ATTRIBUTE::UNSIGNED_INT_2_10_10_10_REV : return "GL_UNSIGNED_INT_2_10_10_10_REV";
  default : return "";
  }
}

